# Generated by Django 4.1.3 on 2023-06-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id_horario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
