# Generated by Django 4.1.3 on 2023-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_horario_id_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='bloques_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='bloques_totales',
            field=models.IntegerField(),
        ),
    ]
