# Generated by Django 4.1.3 on 2023-06-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_horario_bloques_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupos',
            name='cupos_disponibles',
        ),
        migrations.RemoveField(
            model_name='cupos',
            name='hora',
        ),
    ]
