# Generated by Django 4.1.3 on 2023-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cliente_rol_usm_remove_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='día',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
