# Generated by Django 4.1.3 on 2023-07-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horario_día'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='día',
            new_name='dia',
        ),
    ]
